name: cron
on:
  schedule:
    - cron: "*/1 * * * *"
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - name: curly
        run: |
          curl -m 30 http://unsolved-dew.000webhostapp.com/index.php?cron=cron
